#!/bin/bash

set -e

cd /var/www/html/

{ \
    echo "# Generated by $0"; \
    find addons/ -maxdepth 5 -name library -type d  | grep -v .git | sed 's#/library$##'; \
} > ./xenforo/internal_data/addons.txt
