FROM xfrocks/xenforo:php-apache-7.2.12b

RUN apt-get update \
    && apt-get install -y gnupg \
    && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
    && apt-get install -y npm \
    && npm install uglify-js -g \
    && rm -rf /var/lib/apt/lists/*

ENV DEVHELPER_PHP_APACHE_VERSION_ID 2018120601

COPY docker/* /usr/local/bin/
RUN chmod +x /usr/local/bin/*.sh

RUN useradd --uid 1000 uid1000 \
    && useradd --uid 1001 uid1001 \
    && useradd --uid 1002 uid1002 \
    && useradd --uid 501 uid501

RUN echo 'PassEnv DEVHELPER_PHP_APACHE_VERSION_ID' >> /etc/apache2/mods-available/env.conf; \
    a2enmod env rewrite

CMD ["/usr/local/bin/cmd.sh"]
