FROM xfrocks/xenforo:php-apache-7.1.8

RUN apt-get update && apt-get install -y \
        npm \
    && a2enmod rewrite \
    && npm install uglify-js -g \
    && pear install PHP_CodeSniffer \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install apcu \
    && docker-php-ext-enable apcu

COPY docker/* /usr/local/bin/
RUN chmod +x /usr/local/bin/cmd.sh \
    && chmod +x /usr/local/bin/find-addons2.sh

CMD ["/usr/local/bin/cmd.sh"]
