#!/bin/bash

ADDON_ID=""
PATH_TO_XENFORO=""

if [ $# -ge 2 ]; then

    if [ -d "$1" ]; then
        echo $1 already exists! Quit now...
        exit 1
    else
        ADDON_ID="$1"
    fi

    if [ -d "$2" ]; then
        if [ -d "$2/library/" ]; then
            if [ ! -d "$2/library/${ADDON_ID}" ]; then
                PATH_TO_XENFORO="$2"
            else
                echo "$2/library/${ADDON_ID}" already exists?!
                exit 1
            fi
        else
            echo "$2/library/" does not exists! Quit now...
            exit 1
        fi
    else
        echo $2 does not exists! Quit now...
        exit 1
    fi

    # get the addon directory by replace all "_" with "/"
    # we will get a sub directory structure with this kind of subsitution
    # the DevHelper add-on uses a similar structure...
    ADDON_DIR=${ADDON_ID//_/\/}
    
    echo Prepare to enter your password, using sudo command a lot now...
    sudo mkdir -p -m 0777 "${ADDON_DIR}"
    sudo mkdir -p -m 0777 "${ADDON_DIR}/repo/library/${ADDON_DIR}"
    sudo mkdir -p -m 0777 "${ADDON_DIR}/repo/js/${ADDON_DIR}"
    sudo chown -R $USER "${ADDON_DIR}"
    
    sudo ln -s "${PWD}/${ADDON_DIR}/repo/library/${ADDON_DIR}" "${PATH_TO_XENFORO}/library/${ADDON_DIR}"
    sudo ln -s "${PWD}/${ADDON_DIR}/repo/js/${ADDON_DIR}" "${PATH_TO_XENFORO}/js/${ADDON_DIR}"
    sudo chown -h $USER "${PATH_TO_XENFORO}/library/${ADDON_DIR}"
    sudo chown -h $USER "${PATH_TO_XENFORO}/js/${ADDON_DIR}"
    sudo echo "${ADDON_DIR}/*" >> "${PATH_TO_XENFORO}/library/.gitignore"
    sudo echo "${ADDON_DIR}/*" >> "${PATH_TO_XENFORO}/js/.gitignore"

    cd "${ADDON_DIR}/repo/"
    git init
    echo '.DS_Store' >> .gitignore
    # ignore the files generated by DevHelper
    echo '*.devhelper' >> .gitignore
    echo "library/${ADDON_DIR}/DevHelper/Generated/*" >> .gitignore
    git add .
    git commit -m 'Initialized by xf-new-addon script'

    echo Done!
else
    echo USAGE: $0 [addOnId] [path/to/xenforo/root]
fi
